import GSAP from "./lib/gsap";
import PageTransition from "./utils/pageTransition";
import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PageTransition>
          <GSAP>
            <Header />
            {children}
            <Footer />
          </GSAP>
        </PageTransition>
      </body>
    </html>
  );
}
